import{a as w,S as q,i as s}from"./assets/vendor-B5nsgUv9.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))i(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function n(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(o){if(o.ep)return;o.ep=!0;const r=n(o);fetch(o.href,r)}})();const v="46160270-245e238467519bdf1432473a7",M="https://pixabay.com/api/";async function p(e,t=1){const n={key:v,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t};return(await w.get(M,{params:n})).data}let P=new q(".gallery a.gallery-link",{captionsData:"alt",captionDelay:250});function g(e){const t=document.querySelector(".gallery"),n=e.map(({webformatURL:i,largeImageURL:o,tags:r,likes:l,views:b,comments:L,downloads:S})=>`
      <li class="gallery-item">
        <a href="${o}" class="gallery-link">
          <img 
            src="${i}" 
            alt="${r}" 
            loading="lazy"
          />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b><span>${l}</span></p>
          <p class="info-item"><b>Views</b><span>${b}</span></p>
          <p class="info-item"><b>Comments</b><span>${L}</span></p>
          <p class="info-item"><b>Downloads</b><span>${S}</span></p>
        </div>
      </li>
    `).join("");t.insertAdjacentHTML("beforeend",n),P.refresh()}function B(){const e=document.querySelector(".gallery");e.innerHTML=""}function h(){document.querySelector(".loader").classList.remove("is-hidden")}function c(){document.querySelector(".loader").classList.add("is-hidden")}function f(){document.querySelector(".load-more").classList.remove("is-hidden")}function u(){document.querySelector(".load-more").classList.add("is-hidden")}const R=document.querySelector(".form"),m=document.querySelector('input[name="search-text"]'),E=document.querySelector(".load-more");let d="",a=1;const y=15;R.addEventListener("submit",$);E.addEventListener("click",O);async function $(e){if(e.preventDefault(),d=m.value.trim(),d===""){s.warning({message:"Please enter a search query!",position:"topRight"});return}a=1,B(),u(),h();try{const t=await p(d,a);if(t.hits.length===0){c(),s.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g(t.hits),c();const n=Math.ceil(t.totalHits/y);a>=n?(u(),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):f(),m.value=""}catch(t){c(),s.error({message:"Something went wrong. Please try again later!",position:"topRight"}),console.error("Error fetching images:",t)}}async function O(){a++,u(),h();try{const e=await p(d,a);g(e.hits),c(),x();const t=Math.ceil(e.totalHits/y);a>=t?(u(),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",color:"blue"})):f()}catch(e){c(),s.error({message:"Something went wrong while loading more images!",position:"topRight"}),console.error("Error loading more images:",e)}}function x(){const e=document.querySelector(".gallery-item");if(e){const t=e.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
